/**
 * 채널 페이지에서 최신 영상 ID를 추출하고 oEmbed로 제목·썸네일을 받아
 * src/lib/data/youtube-cache.ts에 정적 데이터로 기록.
 *
 * Usage:
 *   node scripts/refresh-youtube.mjs            # default channel @with5340
 *   node scripts/refresh-youtube.mjs <channel>  # other handle
 */

import { writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const HANDLE = process.argv[2] ?? '@with5340'
const OUT = path.join(__dirname, '..', 'src', 'lib', 'data', 'youtube-cache.ts')

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36'

async function getChannelVideoIds(handle) {
  const url = `https://www.youtube.com/${handle}/videos`
  const res = await fetch(url, { headers: { 'User-Agent': UA } })
  if (!res.ok) throw new Error(`channel page HTTP ${res.status}`)
  const html = await res.text()
  // The page lists videos in order (newest first) inside ytInitialData.
  // Extract videoId + title pairs in document order, dedupe preserving order.
  const seen = new Set()
  const ordered = []
  const pairRe = /"videoId":"([A-Za-z0-9_-]{11})"/g
  let m
  while ((m = pairRe.exec(html)) !== null) {
    if (!seen.has(m[1])) {
      seen.add(m[1])
      ordered.push(m[1])
    }
  }
  return ordered
}

async function getMeta(id) {
  const url = `https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${id}&format=json`
  const res = await fetch(url, { headers: { 'User-Agent': UA } })
  if (!res.ok) throw new Error(`oembed ${id} HTTP ${res.status}`)
  return await res.json()
}

const ids = (await getChannelVideoIds(HANDLE)).slice(0, 10)
console.log(`[refresh-youtube] ${ids.length} videos from ${HANDLE}`)

const videos = []
for (const id of ids) {
  try {
    const meta = await getMeta(id)
    videos.push({
      id,
      title: meta.title,
      published: new Date().toISOString(),
      thumbnail: `https://img.youtube.com/vi/${id}/hqdefault.jpg`,
      url: `https://www.youtube.com/watch?v=${id}`,
    })
    console.log(`  ✓ ${id}  ${meta.title.slice(0, 50)}…`)
  } catch (e) {
    console.warn(`  ✗ ${id}  ${e?.message ?? e}`)
  }
}

const ts = `/**
 * Static cache of the latest YouTube videos for the 이권재 오산시장 channel.
 * Generated by scripts/refresh-youtube.mjs — do not edit by hand.
 * Refresh by running: \`node scripts/refresh-youtube.mjs\`
 */

import type { YoutubeVideo } from '@/lib/youtube'

export const YOUTUBE_VIDEOS: YoutubeVideo[] = ${JSON.stringify(videos, null, 2)}
`

await writeFile(OUT, ts, 'utf8')
console.log(`[refresh-youtube] wrote ${videos.length} videos to ${OUT}`)
process.exit(0)
