export type PressCategory = '정책' | '칼럼'

export interface PressItem {
  id: string
  category: PressCategory
  title: string
  body: string
  publishedAt: string
  mediaLinks: { name: string; url: string }[]
  /** Optional thumbnail path under /public/images/press/ */
  thumbnail?: string
}

/** Generated by scripts/build-press-data.mjs / augment-press-data.mjs / add-column-articles.mjs — do not edit by hand. */
export const pressItems: PressItem[] = [
  {
    "id": "pr_20260520_aug24",
    "category": "정책",
    "title": "이권재 오산시장 후보, 양산·세교2 각급 학교 확충 성과, 세교2지구내 세교2-1 중학교 신설 추진",
    "body": "<p>이권재 오산시장 후보, 양산·세교2 각급 학교 확충 성과, 세교2지구내 세교2-1 중학교 신설 추진</p><p>관련 보도 1건이 게재되었습니다.</p>",
    "publishedAt": "2026-05-20",
    "mediaLinks": [
      {
        "name": "경기시사투데이",
        "url": "https://www.yitoday.com/news/articleView.html?idxno=535030"
      }
    ],
    "thumbnail": "/images/press/pr_20260520_aug24.jpg"
  },
  {
    "id": "pr_col_20260519_07",
    "category": "칼럼",
    "title": "[6.3 지방선거 이색 공약 후보]",
    "body": "<p>[6.3 지방선거 이색 공약 후보]</p><p>출처: 뉴스비전e</p>",
    "publishedAt": "2026-05-19",
    "mediaLinks": [
      {
        "name": "뉴스비전e",
        "url": "https://www.nvp.co.kr/news/articleView.html?idxno=318185"
      }
    ],
    "thumbnail": "/images/press/pr_col_20260519_07.jpg"
  },
  {
    "id": "pr_20260519_aug22",
    "category": "정책",
    "title": "‘조용호 지지 단톡방에 뜬 게임방 공약’… 이권재 선거캠프 “조직적 허위사실 유포, 수사 의뢰”",
    "body": "<p>‘조용호 지지 단톡방에 뜬 게임방 공약’… 이권재 선거캠프 “조직적 허위사실 유포, 수사 의뢰”</p><p>관련 보도 1건이 게재되었습니다.</p>",
    "publishedAt": "2026-05-19",
    "mediaLinks": [
      {
        "name": "수원화성신문",
        "url": "https://www.esuwon.net/183486"
      }
    ],
    "thumbnail": "/images/press/pr_20260519_aug22.jpg"
  },
  {
    "id": "pr_20260519_aug23",
    "category": "정책",
    "title": "“반려동물과 함께 사는 도시”… 이권재, 펫 인프라 조성 공약",
    "body": "<p>“반려동물과 함께 사는 도시”… 이권재, 펫 인프라 조성 공약</p><p>관련 보도 1건이 게재되었습니다.</p>",
    "publishedAt": "2026-05-19",
    "mediaLinks": [
      {
        "name": "아주경제",
        "url": "https://www.ajunews.com/view/20260519141923705"
      }
    ],
    "thumbnail": "/images/press/pr_20260519_aug23.jpg"
  },
  {
    "id": "pr_20260518_aug18",
    "category": "정책",
    "title": "“시민 삶 바꾸는 건 결국 실행력”…이권재 후보 선거사무소에 정책·격려 방문 이어져",
    "body": "<p>“시민 삶 바꾸는 건 결국 실행력”…이권재 후보 선거사무소에 정책·격려 방문 이어져</p><p>관련 보도 1건이 게재되었습니다.</p>",
    "publishedAt": "2026-05-18",
    "mediaLinks": [
      {
        "name": "경기신문",
        "url": "https://kgnews.co.kr/news/article.html?no=896165"
      }
    ],
    "thumbnail": "/images/press/pr_20260518_aug18.png"
  },
  {
    "id": "pr_20260518_aug20",
    "category": "정책",
    "title": "“대학병원 유치”…이권재 오산시장 후보, 의료 인프라 확충 공약",
    "body": "<p>“대학병원 유치”…이권재 오산시장 후보, 의료 인프라 확충 공약</p><p>관련 보도 1건이 게재되었습니다.</p>",
    "publishedAt": "2026-05-18",
    "mediaLinks": [
      {
        "name": "프레시안",
        "url": "https://www.pressian.com/pages/articles/2026051817552814856"
      }
    ]
  },
  {
    "id": "pr_20260518_aug21",
    "category": "정책",
    "title": "이권재 오산시장 후보 “동탄2 물류센터 백지화, 조용호 후보 입장 밝혀야”",
    "body": "<p>이권재 오산시장 후보 “동탄2 물류센터 백지화, 조용호 후보 입장 밝혀야”</p><p>관련 보도 1건이 게재되었습니다.</p>",
    "publishedAt": "2026-05-18",
    "mediaLinks": [
      {
        "name": "네이트/동행미디어시대",
        "url": "https://news.nate.com/view/20260518n23511"
      }
    ],
    "thumbnail": "/images/press/pr_20260518_aug21.jpg"
  },
  {
    "id": "pr_col_20260517_06",
    "category": "칼럼",
    "title": "[6.3지선 출마 합니다]  ☆이권재 국민의 힘 경기도 오산시장 후보",
    "body": "<p>[6.3지선 출마 합니다]  ☆이권재 국민의 힘 경기도 오산시장 후보</p><p>출처: 뉴스비전e</p>",
    "publishedAt": "2026-05-17",
    "mediaLinks": [
      {
        "name": "뉴스비전e",
        "url": "https://www.nvp.co.kr/news/articleView.html?idxno=318167"
      }
    ],
    "thumbnail": "/images/press/pr_col_20260517_06.jpg"
  },
  {
    "id": "pr_20260517_aug19",
    "category": "정책",
    "title": "“청년이 머물고 성장하는 도시”… 이권재, 청년 자립·복지 공약 발표",
    "body": "<p>“청년이 머물고 성장하는 도시”… 이권재, 청년 자립·복지 공약 발표</p><p>관련 보도 1건이 게재되었습니다.</p>",
    "publishedAt": "2026-05-17",
    "mediaLinks": [
      {
        "name": "비욘드포스트",
        "url": "https://www.beyondpost.co.kr/view.php?ud=2026051713473921944c878f8fa1_30"
      }
    ],
    "thumbnail": "/images/press/pr_20260517_aug19.jpg"
  },
  {
    "id": "pr_20260515_13",
    "category": "정책",
    "title": "위기가구 즉시 파악 희망 콜센터 설치 공약",
    "body": "<p>위기가구 즉시 파악 희망 콜센터 설치 공약</p><p>관련 보도 1건이 게재되었습니다.</p>",
    "publishedAt": "2026-05-15",
    "mediaLinks": [
      {
        "name": "YTN",
        "url": "https://www.ytn.co.kr/_ln/0115_202605150919326782"
      },
      {
        "name": "미디어와이",
        "url": "https://www.mediawhy.com/news/articleView.html?idxno=131297"
      }
    ],
    "thumbnail": "/images/press/pr_20260515_13.jpg"
  },
  {
    "id": "pr_20260515_aug17",
    "category": "정책",
    "title": "“사교육 없이도 공부한다”… 이권재, 자기주도·맞춤교육 공약 발표",
    "body": "<p>“사교육 없이도 공부한다”… 이권재, 자기주도·맞춤교육 공약 발표</p><p>관련 보도 1건이 게재되었습니다.</p>",
    "publishedAt": "2026-05-15",
    "mediaLinks": [
      {
        "name": "중앙뉴스타임스",
        "url": "https://www.jnewstimes.com/news/article.html?no=706722"
      }
    ],
    "thumbnail": "/images/press/pr_20260515_aug17.jpg"
  },
  {
    "id": "pr_20260514_12",
    "category": "정책",
    "title": "“아이와 엄마가 행복한 도시 만든다”… 이권재, 출산·보육 공약 발표",
    "body": "<p>“아이와 엄마가 행복한 도시 만든다”… 이권재, 출산·보육 공약 발표</p><p>관련 보도 4건이 게재되었습니다.</p>",
    "publishedAt": "2026-05-14",
    "mediaLinks": [
      {
        "name": "비욘드포스트",
        "url": "https://www.beyondpost.co.kr/view.php?ud=2026051320484680964c878f8fa1_30"
      },
      {
        "name": "아시아타임즈",
        "url": "https://www.asiatime.co.kr/article/20260514500128"
      },
      {
        "name": "중부일보",
        "url": "https://www.joongboo.com/news/articleView.html?idxno=363725712"
      },
      {
        "name": "뉴스프리존",
        "url": "https://www.newsfreezone.co.kr/news/articleView.html?idxno=689718"
      },
      {
        "name": "뉴스동포나루",
        "url": "https://www.newsdongponaroo.com/sub_read_amp.html?uid=3796"
      }
    ],
    "thumbnail": "/images/press/pr_20260514_12.jpg"
  },
  {
    "id": "pr_20260514_aug16",
    "category": "정책",
    "title": "“통학버스 전역 확대”… 이권재, 청소년복지 공약 발표",
    "body": "<p>“통학버스 전역 확대”… 이권재, 청소년복지 공약 발표</p><p>관련 보도 1건이 게재되었습니다.</p>",
    "publishedAt": "2026-05-14",
    "mediaLinks": [
      {
        "name": "다음/중부일보",
        "url": "https://v.daum.net/v/WUG1myHlCa?f=p"
      }
    ],
    "thumbnail": "/images/press/pr_20260514_aug16.jpg"
  },
  {
    "id": "pr_20260513_11",
    "category": "정책",
    "title": "“경부축 공간 잇는다”…이권재, ‘고속도로·철도 지하화’ 공약",
    "body": "<p>“경부축 공간 잇는다”…이권재, ‘고속도로·철도 지하화’ 공약</p><p>관련 보도 2건이 게재되었습니다.</p>",
    "publishedAt": "2026-05-13",
    "mediaLinks": [
      {
        "name": "스포츠서울",
        "url": "https://www.sportsseoul.com/news/read/1608933"
      },
      {
        "name": "뉴시스",
        "url": "https://www.newsis.com/view/NISX20260513_0003627765"
      },
      {
        "name": "경기일보",
        "url": "https://www.kyeonggi.com/article/20260513580242"
      }
    ],
    "thumbnail": "/images/press/pr_20260513_11.jpg"
  },
  {
    "id": "pr_20260513_aug14",
    "category": "정책",
    "title": "“오색시장 살린다”… 이권재, 전통시장 활성화 ‘투트랙’ 추진",
    "body": "<p>“오색시장 살린다”… 이권재, 전통시장 활성화 ‘투트랙’ 추진</p><p>관련 보도 1건이 게재되었습니다.</p>",
    "publishedAt": "2026-05-13",
    "mediaLinks": [
      {
        "name": "중앙뉴스타임스",
        "url": "https://www.jnewstimes.com/news/article.html?no=705574"
      }
    ],
    "thumbnail": "/images/press/pr_20260513_aug14.jpg"
  },
  {
    "id": "pr_20260513_aug15",
    "category": "정책",
    "title": "다양한 시민사회단체·직능단체, 이권재 후보 선거사무소 찾아 응원 이어져",
    "body": "<p>다양한 시민사회단체·직능단체, 이권재 후보 선거사무소 찾아 응원 이어져</p><p>관련 보도 1건이 게재되었습니다.</p>",
    "publishedAt": "2026-05-13",
    "mediaLinks": [
      {
        "name": "화성저널",
        "url": "https://www.hsj.co.kr/news/articleView.html?idxno=51783"
      }
    ],
    "thumbnail": "/images/press/pr_20260513_aug15.png"
  },
  {
    "id": "pr_col_20260512_05",
    "category": "칼럼",
    "title": "[김창권의 6.3현장체크 ] 6·3 지방선거 오산의 선택, ‘검증된 리더십’인가 ‘구태의 반복’인가",
    "body": "<p>[김창권의 6.3현장체크 ] 6·3 지방선거 오산의 선택, ‘검증된 리더십’인가 ‘구태의 반복’인가</p><p>출처: 뉴스비전e</p>",
    "publishedAt": "2026-05-12",
    "mediaLinks": [
      {
        "name": "뉴스비전e",
        "url": "https://www.nvp.co.kr/news/articleView.html?idxno=318103"
      }
    ],
    "thumbnail": "/images/press/pr_col_20260512_05.jpg"
  },
  {
    "id": "pr_col_20260512_04",
    "category": "칼럼",
    "title": "☆6.3 지방선거 이것이 공약이다",
    "body": "<p>☆6.3 지방선거 이것이 공약이다</p><p>출처: 뉴스비전e</p>",
    "publishedAt": "2026-05-12",
    "mediaLinks": [
      {
        "name": "뉴스비전e",
        "url": "https://www.nvp.co.kr/news/articleView.html?idxno=318112"
      }
    ],
    "thumbnail": "/images/press/pr_col_20260512_04.jpg"
  },
  {
    "id": "pr_20260512_10",
    "category": "정책",
    "title": "이권재 오산시장 후보, ‘종합스포츠타운’ 건립 공약",
    "body": "<p>이권재 오산시장 후보, ‘종합스포츠타운’ 건립 공약</p><p>관련 보도 2건이 게재되었습니다.</p>",
    "publishedAt": "2026-05-12",
    "mediaLinks": [
      {
        "name": "스포츠서울",
        "url": "https://www.sportsseoul.com/news/read/1608698"
      },
      {
        "name": "팍스경제",
        "url": "https://www.paxetv.com/news/articleView.html?idxno=271800"
      },
      {
        "name": "경기신문",
        "url": "https://www.kgnews.co.kr/news/article.html?no=895472"
      }
    ],
    "thumbnail": "/images/press/pr_20260512_10.jpg"
  },
  {
    "id": "pr_20260512_aug13",
    "category": "정책",
    "title": "“e스포츠·AI로 북부 바꾼다”…이권재 오산시장 후보, 세교터미널 부지 신산업 거점 공약",
    "body": "<p>“e스포츠·AI로 북부 바꾼다”…이권재 오산시장 후보, 세교터미널 부지 신산업 거점 공약</p><p>관련 보도 1건이 게재되었습니다.</p>",
    "publishedAt": "2026-05-12",
    "mediaLinks": [
      {
        "name": "한국글로벌뉴스",
        "url": "https://www.kgfnews.com/mobile/article.html?no=458484"
      }
    ],
    "thumbnail": "/images/press/pr_20260512_aug13.jpg"
  },
  {
    "id": "pr_20260512_aug25",
    "category": "정책",
    "title": "이권재 오산시장 후보, ‘직장운동경기부 스포츠단 창설’ 공약 발표",
    "body": "<p>이권재 오산시장 후보, ‘직장운동경기부 스포츠단 창설’ 공약 발표</p><p>관련 보도 1건이 게재되었습니다.</p>",
    "publishedAt": "2026-05-12",
    "mediaLinks": [
      {
        "name": "팍스경제TV",
        "url": "https://www.paxetv.com/news/articleView.html?idxno=271826"
      }
    ],
    "thumbnail": "/images/press/pr_20260512_aug25.jpg"
  },
  {
    "id": "pr_20260511_09",
    "category": "정책",
    "title": "“시민 곁에서 함께 뛰어온 사람”…오산 각계 시민사회·생활단체 발걸음 이어져",
    "body": "<p>“시민 곁에서 함께 뛰어온 사람”…오산 각계 시민사회·생활단체 발걸음 이어져</p><p>관련 보도 2건이 게재되었습니다.</p>",
    "publishedAt": "2026-05-11",
    "mediaLinks": [
      {
        "name": "비욘드포스트",
        "url": "https://www.beyondpost.co.kr/view.php?ud=2026051110485766284c878f8fa1_30"
      },
      {
        "name": "경인방송",
        "url": "https://news.ifm.kr/news/articleView.html?idxno=470693"
      },
      {
        "name": "경기IN",
        "url": "https://www.gipress.com/603786"
      }
    ],
    "thumbnail": "/images/press/pr_20260511_09.jpg"
  },
  {
    "id": "pr_20260511_aug12",
    "category": "정책",
    "title": "“어르신 이동권 보장 강화”… 이권재, 교통비 지원·면허반납 확대 공약",
    "body": "<p>“어르신 이동권 보장 강화”… 이권재, 교통비 지원·면허반납 확대 공약</p><p>관련 보도 1건이 게재되었습니다.</p>",
    "publishedAt": "2026-05-11",
    "mediaLinks": [
      {
        "name": "중앙뉴스타임스",
        "url": "https://www.jnewstimes.com/news/article.html?no=704608"
      }
    ],
    "thumbnail": "/images/press/pr_20260511_aug12.jpg"
  },
  {
    "id": "pr_col_20260510_03",
    "category": "칼럼",
    "title": "[6.3지방선거 현장이슈] 이권재 국민의 힘 오산시장 후보의 약속, 세교3지구 재지정과 인프라 패키지 확충",
    "body": "<p>[6.3지방선거 현장이슈] 이권재 국민의 힘 오산시장 후보의 약속, 세교3지구 재지정과 인프라 패키지 확충</p><p>출처: 뉴스비전e</p>",
    "publishedAt": "2026-05-10",
    "mediaLinks": [
      {
        "name": "뉴스비전e",
        "url": "https://www.nvp.co.kr/news/articleView.html?idxno=318090"
      }
    ],
    "thumbnail": "/images/press/pr_col_20260510_03.jpg"
  },
  {
    "id": "pr_20260510_aug09",
    "category": "정책",
    "title": "오산대역 상권 상인들·체육인·봉사단체 잇단 방문…이권재 후보 선거사무소 현장 소통 이어져",
    "body": "<p>오산대역 상권 상인들·체육인·봉사단체 잇단 방문…이권재 후보 선거사무소 현장 소통 이어져</p><p>관련 보도 1건이 게재되었습니다.</p>",
    "publishedAt": "2026-05-10",
    "mediaLinks": [
      {
        "name": "경기중앙신문",
        "url": "https://www.ggjapp.com/news/articleView.html?idxno=229797"
      }
    ],
    "thumbnail": "/images/press/pr_20260510_aug09.png"
  },
  {
    "id": "pr_20260510_aug10",
    "category": "정책",
    "title": "오산역 일대 대개조 공약… 이권재, 역세권 개발 프로젝트 발표",
    "body": "<p>오산역 일대 대개조 공약… 이권재, 역세권 개발 프로젝트 발표</p><p>관련 보도 1건이 게재되었습니다.</p>",
    "publishedAt": "2026-05-10",
    "mediaLinks": [
      {
        "name": "경기중앙신문",
        "url": "https://www.ggjapp.com/news/articleView.html?idxno=229795"
      }
    ],
    "thumbnail": "/images/press/pr_20260510_aug10.png"
  },
  {
    "id": "pr_20260510_aug11",
    "category": "정책",
    "title": "이권재 “오산시민 희생 안 된다”… 정명근 후보 측 ‘자치권 침해’ 주장에 반박",
    "body": "<p>이권재 “오산시민 희생 안 된다”… 정명근 후보 측 ‘자치권 침해’ 주장에 반박</p><p>관련 보도 1건이 게재되었습니다.</p>",
    "publishedAt": "2026-05-10",
    "mediaLinks": [
      {
        "name": "경인투데이",
        "url": "https://www.kyungintoday.com/103454"
      }
    ],
    "thumbnail": "/images/press/pr_20260510_aug11.jpg"
  },
  {
    "id": "pr_col_20260508_02",
    "category": "칼럼",
    "title": "[6.3지방선거 이것이 공약이다] 오산의 미래, ‘반도체·소부장 특화도시’에 사활을 걸어야 하는 이유",
    "body": "<p>[6.3지방선거 이것이 공약이다] 오산의 미래, ‘반도체·소부장 특화도시’에 사활을 걸어야 하는 이유</p><p>출처: 뉴스비전e</p>",
    "publishedAt": "2026-05-08",
    "mediaLinks": [
      {
        "name": "뉴스비전e",
        "url": "https://www.nvp.co.kr/news/articleView.html?idxno=318075"
      }
    ],
    "thumbnail": "/images/press/pr_col_20260508_02.jpg"
  },
  {
    "id": "pr_20260508_08",
    "category": "정책",
    "title": "이권재 오산시장 후보, 세교2신도시 관련“경찰지구대·119안전센터·도서관·복합문화센터 패키지로 챙길 것”",
    "body": "<p>이권재 오산시장 후보, 세교2신도시 관련“경찰지구대·119안전센터·도서관·복합문화센터 패키지로 챙길 것”</p><p>관련 보도 1건이 게재되었습니다.</p>",
    "publishedAt": "2026-05-08",
    "mediaLinks": [
      {
        "name": "아주경제",
        "url": "https://www.ajunews.com/view/20260508172944333"
      }
    ],
    "thumbnail": "/images/press/pr_20260508_08.jpg"
  },
  {
    "id": "pr_20260508_aug08",
    "category": "정책",
    "title": "이권재 오산시장 후보, 세교2신도시 관련 “경찰지구대·119안전센터·도서관·복합문화센터 패키지로 챙길 것”",
    "body": "<p>이권재 오산시장 후보, 세교2신도시 관련 “경찰지구대·119안전센터·도서관·복합문화센터 패키지로 챙길 것”</p><p>관련 보도 1건이 게재되었습니다.</p>",
    "publishedAt": "2026-05-08",
    "mediaLinks": [
      {
        "name": "경기타임스",
        "url": "https://www.ggtimes.co.kr/news/articleView.html?idxno=388694"
      }
    ],
    "thumbnail": "/images/press/pr_20260508_aug08.png"
  },
  {
    "id": "pr_20260507_07",
    "category": "정책",
    "title": "“365 언제나 돌봄 완성”…이권재, 24시간 보육·긴급돌봄 공약 발표",
    "body": "<p>“365 언제나 돌봄 완성”…이권재, 24시간 보육·긴급돌봄 공약 발표</p><p>관련 보도 2건이 게재되었습니다.</p>",
    "publishedAt": "2026-05-07",
    "mediaLinks": [
      {
        "name": "뉴싯",
        "url": "https://www.newsis.com/view/NISX20260507_0003620242"
      },
      {
        "name": "아주경제",
        "url": "https://www.ajunews.com/view/20260507155255996"
      },
      {
        "name": "오산인터넷뉴스",
        "url": "https://osinews.co.kr/news/view.php?idx=35806"
      }
    ],
    "thumbnail": "/images/press/pr_20260507_07.jpg"
  },
  {
    "id": "pr_20260507_aug06",
    "category": "정책",
    "title": "이권재 오산시장 후보, 총괄선대대책위원회 발대식 개최",
    "body": "<p>이권재 오산시장 후보, 총괄선대대책위원회 발대식 개최</p><p>관련 보도 1건이 게재되었습니다.</p>",
    "publishedAt": "2026-05-07",
    "mediaLinks": [
      {
        "name": "프레시안",
        "url": "https://www.pressian.com/pages/articles/2026050714362191049"
      }
    ]
  },
  {
    "id": "pr_20260507_aug07",
    "category": "정책",
    "title": "“오산과 함께 성정한 사람”…각계 시민 발걸음 이어져",
    "body": "<p>“오산과 함께 성정한 사람”…각계 시민 발걸음 이어져</p><p>관련 보도 1건이 게재되었습니다.</p>",
    "publishedAt": "2026-05-07",
    "mediaLinks": [
      {
        "name": "뉴스뷰",
        "url": "https://www.newsview.co.kr/265441"
      }
    ],
    "thumbnail": "/images/press/pr_20260507_aug07.jpg"
  },
  {
    "id": "pr_col_20260506_01",
    "category": "칼럼",
    "title": "[김창권의 6.3지선 현장체크]",
    "body": "<p>[김창권의 6.3지선 현장체크]</p><p>출처: 인천매거진</p>",
    "publishedAt": "2026-05-06",
    "mediaLinks": [
      {
        "name": "인천매거진",
        "url": "https://www.imaganews.com/news/articleView.html?idxno=11288"
      }
    ],
    "thumbnail": "/images/press/pr_col_20260506_01.jpg"
  },
  {
    "id": "pr_col_20260506_00",
    "category": "칼럼",
    "title": "[김창권 대기자]의 ☆ 6.3지방선거를 달리는 사람들 - 조중동e뉴스",
    "body": "<p>[김창권 대기자]의 ☆ 6.3지방선거를 달리는 사람들 - 조중동e뉴스</p><p>출처: 조중동e뉴스</p>",
    "publishedAt": "2026-05-06",
    "mediaLinks": [
      {
        "name": "조중동e뉴스",
        "url": "https://newskms.com/View.aspx?No=4068207"
      }
    ],
    "thumbnail": "/images/press/pr_col_20260506_00.jpg"
  },
  {
    "id": "pr_20260506_06",
    "category": "정책",
    "title": "이권재 후보 활동 (2026-05-06)",
    "body": "<p>이권재 후보 활동 (2026-05-06)</p><p>관련 보도 1건이 게재되었습니다.</p>",
    "publishedAt": "2026-05-06",
    "mediaLinks": [
      {
        "name": "경기신문",
        "url": "https://www.kgnews.co.kr/news/article.html?no=894425"
      }
    ],
    "thumbnail": "/images/press/pr_20260506_06.jpg"
  },
  {
    "id": "pr_20260505_aug03",
    "category": "정책",
    "title": "개인·법인택시 조합장, 푸른봉사단 이권재 후보 지지 선언",
    "body": "<p>개인·법인택시 조합장, 푸른봉사단 이권재 후보 지지 선언</p><p>관련 보도 1건이 게재되었습니다.</p>",
    "publishedAt": "2026-05-05",
    "mediaLinks": [
      {
        "name": "아시아경제",
        "url": "https://www.asiae.co.kr/article/2026050510261780054"
      }
    ]
  },
  {
    "id": "pr_20260505_aug04",
    "category": "정책",
    "title": "“AI 교육 강화로 미래 인재 양성”… 이권재 교육 혁신 공약 발표",
    "body": "<p>“AI 교육 강화로 미래 인재 양성”… 이권재 교육 혁신 공약 발표</p><p>관련 보도 1건이 게재되었습니다.</p>",
    "publishedAt": "2026-05-05",
    "mediaLinks": [
      {
        "name": "아시아경제",
        "url": "https://www.asiae.co.kr/article/2026050513025299223"
      }
    ],
    "thumbnail": "/images/press/pr_20260505_aug04.jpg"
  },
  {
    "id": "pr_20260505_aug05",
    "category": "정책",
    "title": "이권재 오산시장 예비후보, 오산·화성 통합 시민 의견 최우선",
    "body": "<p>이권재 오산시장 예비후보, 오산·화성 통합 시민 의견 최우선</p><p>관련 보도 1건이 게재되었습니다.</p>",
    "publishedAt": "2026-05-05",
    "mediaLinks": [
      {
        "name": "기호일보/다음",
        "url": "https://v.daum.net/v/8wn22dlwhO?f=p"
      }
    ],
    "thumbnail": "/images/press/pr_20260505_aug05.jpg"
  },
  {
    "id": "pr_20260504_05",
    "category": "정책",
    "title": "이권재 오산시장 후보, 대중교통 혁신공약 발표 “현관 앞에서 시작되는 교통혁신“",
    "body": "<p>이권재 오산시장 후보, 대중교통 혁신공약 발표 “현관 앞에서 시작되는 교통혁신“</p><p>관련 보도 6건이 게재되었습니다.</p>",
    "publishedAt": "2026-05-04",
    "mediaLinks": [
      {
        "name": "경인방송",
        "url": "https://news.ifm.kr/news/articleView.html?idxno=470277"
      },
      {
        "name": "아시아경제",
        "url": "https://www.asiae.co.kr/article/social-general/2026050421294498985"
      },
      {
        "name": "비욘드포스트",
        "url": "https://www.beyondpost.co.kr/view.php?ud=2026050417453659434c878f8fa1_30"
      },
      {
        "name": "팍스경제",
        "url": "https://www.paxetv.com/news/articleView.html?idxno=271228"
      },
      {
        "name": "데일리한국",
        "url": "https://daily.hankooki.com/news/articleView.html?idxno=1363949"
      },
      {
        "name": "더리포트",
        "url": "https://www.thereport.co.kr/news/articleView.html?idxno=87484"
      },
      {
        "name": "경기타임스",
        "url": "https://www.ggtimes.co.kr/news/articleView.html?idxno=388528"
      }
    ],
    "thumbnail": "/images/press/pr_20260504_05.jpg"
  },
  {
    "id": "pr_20260503_04",
    "category": "정책",
    "title": "경부고속도로 오산IC 입체화 이권재가 추진하겠습니다",
    "body": "<p>경부고속도로 오산IC 입체화 이권재가 추진하겠습니다</p><p>관련 보도 4건이 게재되었습니다.</p>",
    "publishedAt": "2026-05-03",
    "mediaLinks": [
      {
        "name": "스포츠서울",
        "url": "https://www.sportsseoul.com/news/read/1606903"
      },
      {
        "name": "기호일보",
        "url": "https://www.kihoilbo.co.kr/news/articleView.html?idxno=3021572"
      },
      {
        "name": "팍스경제",
        "url": "https://www.paxetv.com/news/articleView.html?idxno=271153"
      },
      {
        "name": "아주경제",
        "url": "https://www.ajunews.com/view/20260503141146258"
      }
    ],
    "thumbnail": "/images/press/pr_20260503_04.jpg"
  },
  {
    "id": "pr_20260503_aug02",
    "category": "정책",
    "title": "민선8기 오산시 퇴직 국장단, 이권재 후보 지지 선언",
    "body": "<p>민선8기 오산시 퇴직 국장단, 이권재 후보 지지 선언</p><p>관련 보도 1건이 게재되었습니다.</p>",
    "publishedAt": "2026-05-03",
    "mediaLinks": [
      {
        "name": "아시아경제",
        "url": "https://www.asiae.co.kr/article/social-general/2026050319301307521"
      }
    ],
    "thumbnail": "/images/press/pr_20260503_aug02.jpg"
  },
  {
    "id": "pr_20260430_03",
    "category": "정책",
    "title": "이권재 오산시장 후보, 선거사무소 개소. 본격 선거전 돌입",
    "body": "<p>이권재 오산시장 후보, 선거사무소 개소. 본격 선거전 돌입</p><p>관련 보도 2건이 게재되었습니다.</p>",
    "publishedAt": "2026-04-30",
    "mediaLinks": [
      {
        "name": "경기신문",
        "url": "https://www.kgnews.co.kr/news/article.html?no=894205"
      },
      {
        "name": "전자신문",
        "url": "https://www.etnews.com/20260501000041"
      },
      {
        "name": "시사일보",
        "url": "https://www.shilbo.kr/news/articleView.html?idxno=262861"
      }
    ],
    "thumbnail": "/images/press/pr_20260430_03.jpg"
  },
  {
    "id": "pr_20260430_aug01",
    "category": "정책",
    "title": "자원봉사단체 굴렁쇠봉사단·이룸봉사단 이권재 후보 지지 선언",
    "body": "<p>자원봉사단체 굴렁쇠봉사단·이룸봉사단 이권재 후보 지지 선언</p><p>관련 보도 1건이 게재되었습니다.</p>",
    "publishedAt": "2026-04-30",
    "mediaLinks": [
      {
        "name": "경인방송",
        "url": "https://news.ifm.kr/news/articleView.html?idxno=470097"
      }
    ],
    "thumbnail": "/images/press/pr_20260430_aug01.jpg"
  },
  {
    "id": "pr_20260429_02",
    "category": "정책",
    "title": "이권재 오산시장 후보 “더 큰 오산, 일 잘하는 시장 선택해달라”",
    "body": "<p>이권재 오산시장 후보 “더 큰 오산, 일 잘하는 시장 선택해달라”</p><p>관련 보도 2건이 게재되었습니다.</p>",
    "publishedAt": "2026-04-29",
    "mediaLinks": [
      {
        "name": "서울경제TV",
        "url": "https://www.sentv.co.kr/article/view/sentv202604290114"
      },
      {
        "name": "OBS",
        "url": "https://www.obsnews.co.kr/news/articleView.html?idxno=1522746"
      },
      {
        "name": "대한경제",
        "url": "https://www.dnews.co.kr/uhtml/view.jsp?idxno=202604292124105150212"
      }
    ],
    "thumbnail": "/images/press/pr_20260429_02.jpg"
  },
  {
    "id": "pr_20260428_01",
    "category": "정책",
    "title": "이권재 오산시장 후보 “누구도 혼자 울지 않는 도시 만들겠다”",
    "body": "<p>이권재 오산시장 후보 “누구도 혼자 울지 않는 도시 만들겠다”</p><p>관련 보도 2건이 게재되었습니다.</p>",
    "publishedAt": "2026-04-28",
    "mediaLinks": [
      {
        "name": "파이낸셜뉴스",
        "url": "https://v.daum.net/v/3aB7rQsAot"
      },
      {
        "name": "아시아경제",
        "url": "https://v.daum.net/v/20260428121346704?f=p"
      },
      {
        "name": "팍스경제TV",
        "url": "https://www.paxetv.com/news/articleView.html?idxno=270810"
      }
    ],
    "thumbnail": "/images/press/pr_20260428_01.jpg"
  },
  {
    "id": "pr_20260428_aug00",
    "category": "정책",
    "title": "이권재 오산시장 후보 “동탄2 물류센터, 전면 백지화 공동 공약 채택하자”… 화성·오산 시장 후보에 공개 제안",
    "body": "<p>이권재 오산시장 후보 “동탄2 물류센터, 전면 백지화 공동 공약 채택하자”… 화성·오산 시장 후보에 공개 제안</p><p>관련 보도 1건이 게재되었습니다.</p>",
    "publishedAt": "2026-04-28",
    "mediaLinks": [
      {
        "name": "경기일보",
        "url": "https://www.kyeonggi.com/article/20260428580466"
      }
    ],
    "thumbnail": "/images/press/pr_20260428_aug00.jpg"
  },
  {
    "id": "pr_20260427_00",
    "category": "정책",
    "title": "이권재 오산시장, 예비후보 등록하고 재선 돌입",
    "body": "<p>이권재 오산시장, 예비후보 등록하고 재선 돌입</p><p>관련 보도 4건이 게재되었습니다.</p>",
    "publishedAt": "2026-04-27",
    "mediaLinks": [
      {
        "name": "파이낸셜뉴스",
        "url": "https://v.daum.net/v/20260427162148029"
      },
      {
        "name": "연합뉴스",
        "url": "https://www.yna.co.kr/view/AKR20260427111600061"
      },
      {
        "name": "기호일보",
        "url": "https://www.kihoilbo.co.kr/news/articleView.html?idxno=3021007"
      },
      {
        "name": "오마이뉴스",
        "url": "https://www.ohmynews.com/NWS_Web/Series/series_premium_pg.aspx?CNTN_CD=A0003228865"
      },
      {
        "name": "경기타임스",
        "url": "https://www.ggtimes.co.kr/news/articleView.html?idxno=388230"
      }
    ],
    "thumbnail": "/images/press/pr_20260427_00.jpg"
  }
]

export function getPressItem(id: string): PressItem | undefined {
  return pressItems.find((p) => p.id === id)
}

export function getAdjacentPress(id: string): {
  prev?: PressItem
  next?: PressItem
} {
  const sorted = [...pressItems].sort((a, b) =>
    a.publishedAt < b.publishedAt ? 1 : -1,
  )
  const idx = sorted.findIndex((p) => p.id === id)
  if (idx === -1) return {}
  return {
    prev: sorted[idx + 1],
    next: sorted[idx - 1],
  }
}

export function formatPressDate(iso: string): string {
  return iso.replace(/-/g, '.')
}
