/**
 * Static cache of the latest YouTube videos for the 이권재 오산시장 channel.
 * Generated by scripts/refresh-youtube.mjs — do not edit by hand.
 * Refresh by running: `node scripts/refresh-youtube.mjs`
 */

import type { YoutubeVideo } from '@/lib/youtube'

export const YOUTUBE_VIDEOS: YoutubeVideo[] = [
  {
    "id": "Gxi6PM2smfw",
    "title": "운암뜰 AI시티와 반도체가 묻고 이권재가 답한다!가 묻고 이권재가 답한다! #이권재 #오산시장 #오산시장후보 #운암뜰 #AI #반도체",
    "published": "2026-05-20T07:04:07.350Z",
    "thumbnail": "https://img.youtube.com/vi/Gxi6PM2smfw/hqdefault.jpg",
    "url": "https://www.youtube.com/watch?v=Gxi6PM2smfw"
  },
  {
    "id": "QqByPkGFm5A",
    "title": "출퇴근길과 도로정비가 묻고 이권재가 답한다! #이권재 #오산시장 #오산시장후보 #지하도로 #횡단도로 #오산공사",
    "published": "2026-05-20T07:04:07.442Z",
    "thumbnail": "https://img.youtube.com/vi/QqByPkGFm5A/hqdefault.jpg",
    "url": "https://www.youtube.com/watch?v=QqByPkGFm5A"
  },
  {
    "id": "q1YjH1Cvlu0",
    "title": "이권재와 오산을 살리고! #이권재 #오산시장 #오산시장후보 #기호2번 #더큰오산 #선거송",
    "published": "2026-05-20T07:04:07.527Z",
    "thumbnail": "https://img.youtube.com/vi/q1YjH1Cvlu0/hqdefault.jpg",
    "url": "https://www.youtube.com/watch?v=q1YjH1Cvlu0"
  },
  {
    "id": "eaUPrfTckWU",
    "title": "도시개발과 랜드마크가 묻고 이권재가 답한다! #이권재 #오산시장 #오산시장후보 #세교신도시 #세교3지구 #대중교통 #광역버스",
    "published": "2026-05-20T07:04:07.621Z",
    "thumbnail": "https://img.youtube.com/vi/eaUPrfTckWU/hqdefault.jpg",
    "url": "https://www.youtube.com/watch?v=eaUPrfTckWU"
  },
  {
    "id": "vEvJekVUvi4",
    "title": "세교3지구와 교통이 묻고 이권재가 답한다! #이권재 #오산시장 #오산시장후보 #세교신도시 #세교3지구 #대중교통 #광역버스",
    "published": "2026-05-20T07:04:07.709Z",
    "thumbnail": "https://img.youtube.com/vi/vEvJekVUvi4/hqdefault.jpg",
    "url": "https://www.youtube.com/watch?v=vEvJekVUvi4"
  },
  {
    "id": "6Vqxb-1fcbY",
    "title": "말보다 실력, 정치보다 민생입니다. #이권재 #오산시장 #오산시장후보 #기호2번 #더큰오산 #오산시민 #민생지원",
    "published": "2026-05-20T07:04:07.803Z",
    "thumbnail": "https://img.youtube.com/vi/6Vqxb-1fcbY/hqdefault.jpg",
    "url": "https://www.youtube.com/watch?v=6Vqxb-1fcbY"
  },
  {
    "id": "q3P0gyZGGvI",
    "title": "겨울에 낭만을 더합니다. 2025 오!해피산타마켓",
    "published": "2026-05-20T07:04:07.893Z",
    "thumbnail": "https://img.youtube.com/vi/q3P0gyZGGvI/hqdefault.jpg",
    "url": "https://www.youtube.com/watch?v=q3P0gyZGGvI"
  },
  {
    "id": "s829hrzNkRs",
    "title": "신입공무원과 함께 나누는 공감의 시간 #오산시장 #이권재 #소통하는시장 #공감의시간 #일상의이야기",
    "published": "2026-05-20T07:04:07.974Z",
    "thumbnail": "https://img.youtube.com/vi/s829hrzNkRs/hqdefault.jpg",
    "url": "https://www.youtube.com/watch?v=s829hrzNkRs"
  },
  {
    "id": "9Cw_PnpE-zs",
    "title": "화성 동탄2신도시  물류센터, 전면 백지화를 촉구합니다! #화성시 #초대형물류센터반대",
    "published": "2026-05-20T07:04:08.070Z",
    "thumbnail": "https://img.youtube.com/vi/9Cw_PnpE-zs/hqdefault.jpg",
    "url": "https://www.youtube.com/watch?v=9Cw_PnpE-zs"
  },
  {
    "id": "--v9qztzdsc",
    "title": "함께 걷는 오늘, 함께 걸어온 시간 - 부부의 날 #오산 #오산시장 #이권재 #부부의날  #가족 #가정의달",
    "published": "2026-05-20T07:04:08.153Z",
    "thumbnail": "https://img.youtube.com/vi/--v9qztzdsc/hqdefault.jpg",
    "url": "https://www.youtube.com/watch?v=--v9qztzdsc"
  }
]
